### ISSUE TITLE
can't get best.pt through utl what you give

### ISSUE THREAD

**Issue by super-AGU** [TexasInstruments/edgeai-yolov5#14]
Inaccessible：
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/latest/edgeai-yolov5/pretrained_models/models/yolov5s6_640_ti_lite/weights/best.pt

thinks very much.

**Comment by dongxiaolong** [comment]
you can download by wget.
example: `wget http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/latest/edgeai-yolov5/pretrained_models/models/yolov5s6_640_ti_lite/weights/best.pt`

**Comment by coordxyz** [comment]
I can't download the pretrained models either.

**Comment by dongxiaolong** [comment]
> I can't download the pretrained models either.

I still can download model through wget. Firstly you should copy the model link adress(right click, than you will see), than use wget. such like `wget http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/latest/edgeai-yolov5/pretrained_models/models/yolov5s6_640_ti_lite/weights/best.pt` on your linux command.

**Comment by debapriyamaji** [comment]
Hi @coordxyz ,

Can you please try this link:

 wget http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/latest/edgeai-yolov5/pretrained_models/checkpoints/detection/coco/edgeai-yolov5/yolov5s6_640_ti_lite/weights/best.pt

Regards, Debapriya
