### ISSUE TITLE
IndexError: index is out of bounds for dimension with size 0

### ISSUE THREAD

**Issue by wangduyang** [TexasInstruments/edgeai-yolov5#15]

**Comment by wangduyang** [comment]
the output image
![zidane](https://user-images.githubusercontent.com/26652416/172284861-034637b2-81ad-4ad8-82c4-54e8f9757c77.jpg)

**Comment by Flashan** [comment]
Hi, I meet the same problem, can i ask how do you fix it?

**Comment by lyg2021** [comment]
Hello, I have the same problem, which occurred after I fixed the # 6948 problem. I would be very grateful if you could tell me your solution.

**Comment by sien110** [comment]
Hi, I meet the same problem, can i ask how do you fix it?

**Comment by whzz101** [comment]
‘parser.add_argument('--kpt-label', default=True,action='store_true', help='use keypoint labels')’
or use command "python detect.py --weights last.pt --kpt-label"
