### ISSUE TITLE
Model makes no object classification

### ISSUE THREAD

**Issue by avickars** [TexasInstruments/edgeai-yolov5#19]
## ❔Question
Just confirming my understanding, that is that the model assumes all objects are humans and thus makes no classification on the type of object correct? (i.e. in contrast to say yolov5 that will also classify the types of objects in the bounding box ~ dog, cat etc)

**Comment by debapriyamaji** [comment]
@avickars Yes you are correct. Since we are performing human pose estimation, the model detects only humans along with their poses.
