### ISSUE TITLE
Some issue:  Convert the onnx model to  tda4 platform( * . bin)

### ISSUE THREAD

**Issue by lilyswang** [TexasInstruments/edgeai-yolov5#2]
## ❔Question
Hi , thanks for  your nice job! I now have some problems with model transformation when I  Convert the onnx model to  tda4 platform( * . bin). I hope to get your advice，thanks a lot.

## Additional context

**TIDL Meta PipeLine (Proto) File  : ../../test/testvecs/config/import/public/onnx/mlh_yolov4/yolov5.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:309] Error parsing text-format tidl_meta_arch.TIDLMetaArch: 54:5: Unknown enumeration value of "CODE_TYPE_YOLO_V5" for field "code_type".
ERROR: google::protobuf::TextFormat::Parse proto file(../../test/testvecs/config/import/public/onnx/mlh_yolov4/yolov5.prototxt) FAILED !!!**

Details  like follows:

![image](https://user-images.githubusercontent.com/30424943/146114198-2781b4c7-5875-460d-a257-276accda9455.png)

**Comment by debapriyamaji** [comment]
Hi,
You are using slightly older sdk. It is supported from 8.0 release onwards.

**Comment by lilyswang** [comment]
@debapriyamaji Thanks a lot. SDK version is not match .^-^
