### ISSUE TITLE
results are error

### ISSUE THREAD

**Issue by xywlpo** [TexasInstruments/edgeai-yolov5#24]
hi, I run your code, but error results was got. I used these following models to run detect.py
![image](https://user-images.githubusercontent.com/728405/172619454-be3ef7c0-ade6-4aca-9ac0-b86d099ec59d.png)

But I got the following results, where was wrong?
<img width="945" alt="image" src="https://user-images.githubusercontent.com/728405/172619985-302c7673-7e5f-4b37-96b6-ee5a16cc12a0.png">
<img width="756" alt="image" src="https://user-images.githubusercontent.com/728405/172620073-54a24b28-835a-488d-9e73-29bac32a1972.png">

**Comment by heylary** [comment]
Please ask which file you are running for key point detection, I am new to this project, but I don't know how to run the detected file.

**Comment by xywlpo** [comment]
> 

I use detect.py to test the image.

**Comment by paleomoon** [comment]
Same issues, seems the keypoints of pretrained model output is wrong.
![zidane](https://user-images.githubusercontent.com/17964314/173320330-352c91dd-0db3-4777-a08b-8708072deed3.jpg)

**Comment by ZhenpengChenCode** [comment]
I ran the Yolov5l6_pose_960x960_GMACS_145.6_AP0.5-0.95_69.4_AP0.5_90.2 model. It was found that the model has the following problems:
1) Background false detection;
2) Sometimes people's face points are abnormal.

![000000000108](https://user-images.githubusercontent.com/15834233/176835576-5ff574bb-b3c9-4efe-810c-dfd8780218ea.jpg)

![000000000251](https://user-images.githubusercontent.com/15834233/176835692-e4a0b68a-b9f6-470a-aacb-ec08fe3f0347.jpg)

![000000000694](https://user-images.githubusercontent.com/15834233/176835798-f49c3387-795a-4451-b3df-613e4aab322c.jpg)

**Comment by debapriyamaji** [comment]
I have updated the models. Let me know if you see any issue with the latest models.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolo-pose-models-and-ckpts
