### ISSUE TITLE
About GMACs reported in the YOLO-Pose paper

### ISSUE THREAD

**Issue by WongKinYiu** [TexasInstruments/edgeai-yolov5#26]
## ❔Question

Why the GMACs of other methods reported in this paper are doubled when compare with GFLOPs reported in original papers.

Usually, FLOPs may = MACs or = 2 * MACs when use different definition. I have not checked which one is reported in the original paper, but it won't be MACs / 2.

**Comment by debapriyamaji** [comment]
@WongKinYiu ,

By definition,  FLOPs = 2 * MACs. For other bottom-up approaches, all reported results are with flip-test. That's why the complexity is doubled.

Regards, Debapriya

**Comment by WongKinYiu** [comment]
Thanks.

**Comment by WongKinYiu** [comment]
@debapriyamaji 

add yolor support.

 |Dataset | Model Name | Input Size | \#Params | GMACS  | AP[0.5:0.95]% | AP50% | AP75% |
|--------|-------------------------------|-----------|-----------|----------|-------------|------|-----|
| COCO | Yolov5m6_pose_960 | 960x960 | 41.4M | **66.3**  | 67.4  | 89.1 | 73.7 |
| COCO | [Yolorp6_pose_960](https://github.com/WongKinYiu/yolor/releases/download/weights/yolor-pose.zip) | 960x960 | 41.6M | **100.6**  | 70.4  | 90.3 | 78.1 |
| COCO | Yolov5l6_pose_960 | 960x960 | 87.0M | **145.6** | 69.4  | 90.2 | 76.1 |

Thanks for your great repo.

**Comment by debapriyamaji** [comment]
@WongKinYiu That's really awesome.  Thanks for training yolor that surpasses yolov5l at lower complexity. Will add these results.

Regards, Debapriya
