### ISSUE TITLE
Could you provide config files?

### ISSUE THREAD

**Issue by atangfan** [TexasInstruments/edgeai-yolov5#30]
Hi, thanks for the great work. I cannot find config yamls like yolov5s6_kpts_ti_lite.yaml and yolov5s6_kpts.yaml from repo and links in README. [models](https://github.com/TexasInstruments/edgeai-yolov5/tree/master/models)/yolov5s.yaml doesn't declare P6, so I assume you have different settings.

Could you provide those yaml? Thank you.

**Comment by 514398473** [comment]
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose/models/hub
You can find it here.

**Comment by atangfan** [comment]
thank you
