### ISSUE TITLE
person pose detect results are error

### ISSUE THREAD

**Issue by baishuang88** [TexasInstruments/edgeai-yolov5#32]
![70c17935ea2092108f1fb764b966d4f](https://user-images.githubusercontent.com/93317020/176439779-51f07ee9-870c-406d-b43b-0405a9704e6e.jpg)

**Comment by debapriyamaji** [comment]
Hi @baishuang88 

Please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

I have updated the other models as well and let me know if you see any issue.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolo-pose-models-and-ckpts


Regards, Debapriya
