### ISSUE TITLE
About retraining the model on the coco data set, there is a problem with the prediction chart after training

### ISSUE THREAD

**Issue by HiiHongFe** [TexasInstruments/edgeai-yolov5#38]
## Additional context
I tried yolov5s6_ pose_ 640_ ti_lite The weight of Lite was fine tuned on the coco data set. I added a larger rotation to the data, and the rotation angle was between [-180-180]. I didn't make any other adjustments except for that. I found that after training, the model seemed to be not friendly to the left eye or left ear, and its key points always shifted a lot. Such a problem also occurred in the picture of reasoning after training. What is this problem? Has the author encountered it? Looking forward to your reply.

**Comment by HiiHongFe** [comment]
before prediction：
![image](https://user-images.githubusercontent.com/44940083/177914843-71cca562-69c1-4cfd-a487-bc0c7eca420c.png)

after prediction：
![image](https://user-images.githubusercontent.com/44940083/177914863-3e857d1d-31a2-43a1-8774-96c7903e2f2a.png)

**Comment by isagastiberri** [comment]
I have the same issue. We already detected the bug in #16 using the inference script. However, like you, I retrained the network and the same mistake is present, so there's some kind of bug affecting those two keypoints. Hopefully soeone is able to find the reason soon, if you have any clue what's happening, please let me know :) 
Thanks!

**Comment by BaofengZan** [comment]
I have the same issue.     Do you have some ways to solve? @HiiHongFe @isagastiberri

**Comment by debapriyamaji** [comment]
Hi,
Can you try any of these models? Let me know if you see any such issues.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

**Comment by K-tang-mkv** [comment]
I got the same problem, i.e., the left eye and ear always can't be detected after retraining a model
