### ISSUE TITLE
detect pose Out of range

### ISSUE THREAD

**Issue by nobody-cheng** [TexasInstruments/edgeai-yolov5#39]
![16a7f92024366dbb89d9476f571f5ea](https://user-images.githubusercontent.com/34908468/178174534-e086402c-14c1-415f-8619-3ae30a75445f.png)
![image](https://user-images.githubusercontent.com/34908468/178174602-37b714b4-86c2-4a94-9cbc-ffad8a26f272.png)

**Comment by debapriyamaji** [comment]
Hi @nobody-cheng 

I have one request: Will you please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

Reards, Debapriya

**Comment by debapriyamaji** [comment]
@nobody-cheng , 

Did it work? Can you please try the other models as well? I have updated them recently and it will be great if you can cross-check it once. E.g with this ckpt.

http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5s6_640_60p7_85p3_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt

**Comment by nobody-cheng** [comment]
> 

![图片](https://user-images.githubusercontent.com/34908468/187662061-bc7b51fe-5607-40c2-b617-f2d2f1987b2c.png)

**Comment by debapriyamaji** [comment]
Hi,
Can you please share a few frames where you are seeing this issue?
