### ISSUE TITLE
keypoint out of range 

### ISSUE THREAD

**Issue by wojiaohumaocheng** [TexasInstruments/edgeai-yolov5#42]
## 🐛 Bug
![c757edf2af15c3a58107955ce0b85c9](https://user-images.githubusercontent.com/25666696/180399918-b7bbcaed-142c-410f-8174-03cce2a6b00e.jpg)

**Comment by debapriyamaji** [comment]
@wojiaohumaocheng 
Please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

I have updated the other models as well and let me know if you see any issue.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolo-pose-models-and-ckpts

Regards, Debapriya
