### ISSUE TITLE
yolo-pose: run detect.py keypoints result  out of range

### ISSUE THREAD

**Issue by StochasticGame** [TexasInstruments/edgeai-yolov5#43]
## ❔Question

![images (11)](https://user-images.githubusercontent.com/23732350/180401005-66b14aa5-d7cf-49e7-bf63-57e29229fdc4.jpg)

![images (7)](https://user-images.githubusercontent.com/23732350/180401034-fd8bcfe8-abdc-4625-ab74-58e9f1f550d6.jpg)

**Comment by debapriyamaji** [comment]
Hi  @StochasticGame 

Please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

I have updated the other models as well and let me know if you see any issue.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolo-pose-models-and-ckpts

Regards, Debapriya
