### ISSUE TITLE
The weight in the “pretrained_models” cannot be downloaded

### ISSUE THREAD

**Issue by glode515** [TexasInstruments/edgeai-yolov5#44]
## ❔Question
In the "pretrained_models",unable to download “best.pt” through the link in the “best.pt.link”.
In the README,"pre trained_models" cannot jump to download weights.
Where do I get the weight to test? Thanks!

**Comment by yumingchen** [comment]
Can you download the pretrained model?
I also had the same problem.

**Comment by lsdbwb** [comment]
can't open the link with browser，you can use "wget"

**Comment by yumingchen** [comment]
I can download the pretrained model by "wget". Thanks.
