### ISSUE TITLE
Specific keypoint out of the boundingbox range

### ISSUE THREAD

**Issue by BruceZane1** [TexasInstruments/edgeai-yolov5#45]
After running the demo code with test pictures, there often exist specific keypoints which is out of the boundingbox range. I see some other people raising the similar questions but no exact solution is given until now.

**Comment by debapriyamaji** [comment]
Hi @BruceZane1 

I have one request: Will you please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

Reards, Debapriya

**Comment by StochasticGame** [comment]
@debapriyamaji Replacing yolov5 with yolov7 model on the basis of this project can solve the problem of key points out of range
https://github.com/WongKinYiu/yolov7

The network structure of yolov5 and yolov7 is very similar, you just need to replace the corresponding code

**Comment by Michelvl92** [comment]
@debapriyamaji the ti-lite models work. When do you plan to release the non-ti models?

**Comment by debapriyamaji** [comment]
Hi @Michelvl92 ,
I have updated the paths for the non-ti models. Can you please try it once and let me know if you see any problem?
