### ISSUE TITLE
coco_kpts.yaml ?

### ISSUE THREAD

**Issue by sunlinlin-aragon** [TexasInstruments/edgeai-yolov5#51]
## ❔Question
coco_kpts.yaml ?

## Additional context
hello  author， where is coco_kpts.yaml ?

**Comment by SashaAlderson** [comment]
@sunlinlin-aragon  I'm not the author but https://github.com/TexasInstruments/edgeai-yolov5/blob/yolo-pose/data/coco_kpts.yaml

**Comment by sunlinlin-aragon** [comment]
@SashaAlderson  Thank you very much.

**Comment by sunlinlin-aragon** [comment]
@SashaAlderson hello，please，  Where do you have 【yolov5l6_ kpts.Yaml， yolov5m6_kpts.yaml， yolov5s6_kpts.yaml】 these three files

**Comment by SashaAlderson** [comment]
@sunlinlin-aragon Hi, https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose/models/hub

**Comment by sunlinlin-aragon** [comment]
@debapriyamaji  Thank you！
