### ISSUE TITLE
How to download the pretrained model?

### ISSUE THREAD

**Issue by yumingchen** [TexasInstruments/edgeai-yolov5#53]
## ❔Question
How to download the pretrained model?

## Additional context

I can't download the pretrained model through the link provided by the author.
link: 
https://downloads.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5s6_640_57p5_84p3_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt

**Comment by debapriyamaji** [comment]
@yumingchen ,
I have updated the paths. Can you please try it out now?

**Comment by yumingchen** [comment]
I still can't download the yolo-pose pretrained model.
link: 
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5s6_640_60p7_85p3_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt

**Comment by yumingchen** [comment]
I&nbsp;still&nbsp;can't&nbsp;download&nbsp;the&nbsp;yolo-pose&nbsp;pretrained&nbsp;model.


---Original---
From: ***@***.***&gt;
Date: Sun, Aug 21, 2022 18:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [TexasInstruments/edgeai-yolov5] How to download the pretrainedmodel? (Issue #53)




 
@yumingchen ,
 I have updated the paths. Can you please try it out now?
 
&mdash;

**Comment by yumingchen** [comment]
> @yumingchen , I have updated the paths. Can you please try it out now?

I can download the pretrained model by "wget". Thanks.

**Comment by GeT-RiGhTTT** [comment]
> > @yumingchen , I have updated the paths. Can you please try it out now?
> 
> I can download the pretrained model by "wget". Thanks.
Can u share me, please, I can't download it.

**Comment by yumingchen** [comment]
> > > @yumingchen , I have updated the paths. Can you please try it out now?
> > 
> > 
> > I can download the pretrained model by "wget". Thanks.
> > Can u share me, please, I can't download it.

wget http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5s6_640_60p7_85p3_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt

**Comment by GeT-RiGhTTT** [comment]
Got it, thank you for your review.
