### ISSUE TITLE
This points is not correct?

### ISSUE THREAD

**Issue by cyymt** [TexasInstruments/edgeai-yolov5#56]
![image](https://user-images.githubusercontent.com/32134215/186060931-94373937-5cc4-43c3-b276-236c2a2e5ad9.png)

**Comment by debapriyamaji** [comment]
@cyymt ,
Which model did you try? Did you take the latest models and try it out again? E.g.
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/other/best_models/yolov5s6_640_60p7_85p3_kpts_head_6x_dwconv_3x3_lr_0p01/weights/last.pt


I have one request: Will you please try inference on the *ti-lite models and let me know if you see any issue with them.
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose#yolov5-ti-lite-based-models-and-ckpts

Regards, Debapriya

**Comment by wanglegoc** [comment]
hi @cyymt  do you know why one of the keypoint isn't right? I obtain some results like yours. Thanks

**Comment by debapriyamaji** [comment]
@wanglegoc @cyymt 
Please try the ti-lite model as suggested above.

Can you also share the exact command that you used?
