### ISSUE TITLE
something question about training

### ISSUE THREAD

**Issue by heylary** [TexasInstruments/edgeai-yolov5#58]
## ❔Question
when i run the train.py,it has somthing error, and i think it maybe the dataset's problem, could you please help me= = 

my dataset's format:
![image](https://user-images.githubusercontent.com/34568834/186366051-9cc2dc27-cfc4-404d-95be-e5a2f6b8d717.png)

and i put the coco's img into the images, and i wonder what the annotations contain? and here is the error when i run the train,py
![image](https://user-images.githubusercontent.com/34568834/186361265-02e95703-8928-4748-8351-0eb373b3d05f.png)

## Additional context
and i wonder how to download the   "yolov5s6_kpts.yaml" file ,thankssss you!

**Comment by yyut122** [comment]
What is your training command in console? and your floder structure should correspond to the intro of this repossitory.

eg. My training command is : python train.py --data data/coco_kpts.yaml --cfg models/hub/yolov5s6_kpts.yaml --weights weights/yolov5s6.pt --batch-size 16 --img 640 --kpt-label --epochs 100

Maybe this will help you.

**Comment by heylary** [comment]
> What is your training command in console? and your floder structure should correspond to the intro of this repossitory.
> 
> eg. My training command is : python train.py --data data/coco_kpts.yaml --cfg models/hub/yolov5s6_kpts.yaml --weights weights/yolov5s6.pt --batch-size 16 --img 640 --kpt-label --epochs 100
> 
> Maybe this will help you.

should i put the labels into the images?like the follow format:
![image](https://user-images.githubusercontent.com/34568834/186588171-4bf2e651-09b1-4343-9d32-6bcea903d1d2.png)

i still get the error ... my command is: python train.py --data data/coco_kpts.yaml --cfg models/hub/yolov5s6_kpts.yaml  --batch-size 16 --img 640 --kpt-label --epochs 100 
![image](https://user-images.githubusercontent.com/34568834/186588390-9939a045-1c6e-49fe-b07f-bd0e807c88bb.png)
and thank you!

**Comment by yyut122** [comment]
No, don't mix them. This way is not work.
Your folder structure should be like below.
<img width="563" alt="螢幕擷取畫面 2022-08-25 145829" src="https://user-images.githubusercontent.com/18660724/186596637-fc02cc10-e38d-4737-a323-f082e3e5463f.png">

**Comment by nguyenanhtuan1008** [comment]
@yyut122 annotations_trainval2017 and anotations_test2017 means person_keypoints_train2017.json and person_keypoints_val2017.json?

**Comment by yyut122** [comment]
@nguyenanhtuan1008 I didn't think about training process use which annotations. I just put coco dataset annotations to the right position.
I think you are right training process use person_keypoints_train2017.json and person_keypoints_val2017.json. The exact info is these two files are in annotations folder.

**Comment by yyut122** [comment]
I run training almost every working day. Success training process is like below.
<img width="755" alt="image" src="https://user-images.githubusercontent.com/18660724/186804783-3b1c8fb2-1842-414f-aee6-8cbb5098a550.png">
