### ISSUE TITLE
detect.py

### ISSUE THREAD

**Issue by Flashan** [TexasInstruments/edgeai-yolov5#67]
Traceback (most recent call last):
  File "D:/RunPrograms/edgeai-yolov5-pose/detect.py", line 219, in <module>
    detect(opt=opt)
  File "D:/RunPrograms/edgeai-yolov5-pose/detect.py", line 111, in detect
    scale_coords(img.shape[2:], det[:, 6:], im0.shape, kpt_label=kpt_label, step=3)
  File "D:\RunPrograms\edgeai-yolov5-pose\utils\general.py", line 385, in scale_coords
    coords[:, [0, 2]] -= pad[0]  # x padding
IndexError: index is out of bounds for dimension with size 0

**Comment by MukundSeethamraju** [comment]
having same issue. also, can you add export file to the repository?

**Comment by sinae-noh** [comment]
same issue.. help me

**Comment by lhz-1** [comment]
> Traceback (most recent call last): File "D:/RunPrograms/edgeai-yolov5-pose/detect.py", line 219, in detect(opt=opt) File "D:/RunPrograms/edgeai-yolov5-pose/detect.py", line 111, in detect scale_coords(img.shape[2:], det[:, 6:], im0.shape, kpt_label=kpt_label, step=3) File "D:\RunPrograms\edgeai-yolov5-pose\utils\general.py", line 385, in scale_coords coords[:, [0, 2]] -= pad[0] # x padding IndexError: index is out of bounds for dimension with size 0

I thought this might help you
‘parser.add_argument('--kpt-label',  default=True,action='store_true', help='use keypoint labels')’

**Comment by lhz-1** [comment]
for det_index, (*xyxy, conf, cls) in enumerate(reversed(det[:,:6])):

The value of 109 rows “reversed(det[:,:6])” makes the index different from the “det”，resulting in 119 rows“kpts”and“xyxy” not being the same data

**Comment by kadimakipp** [comment]
add in  models/experimental.py 124 line
```
    for m in model.modules():
        if type(m) in [nn.Hardswish, nn.LeakyReLU, nn.ReLU, nn.ReLU6, nn.SiLU, Detect, Model]:
            m.inplace = inplace  # pytorch 1.7.0 compatibility
        elif type(m) is Conv:
            m._non_persistent_buffers_set = set()  # pytorch 1.6.0 compatibility
        elif type(m) is nn.Upsample and not hasattr(m, 'recompute_scale_factor'):
            m.recompute_scale_factor = None
```

**Comment by gaodaren47297** [comment]
you need to open this argument '--kpt-label'，set it as True
