### ISSUE TITLE
'Detect' object has no attribute 'nkpt'

### ISSUE THREAD

**Issue by rongfal** [TexasInstruments/edgeai-yolov5#71]
Model Summary: 224 layers, 7266973 parameters, 0 gradients
Traceback (most recent call last):
  File "E:/Python/yolo-pose/edgeai-yolov5/detect.py", line 202, in <module>
    detect(opt=opt)
  File "E:/Python/yolo-pose/edgeai-yolov5/detect.py", line 65, in detect
    model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters())))  # run once
  File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 157, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 188, in forward_once
    x = m(x)  # run
  File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 64, in forward
    if self.nkpt is None or self.nkpt==0:
  File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1177, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Detect' object has no attribute 'nkpt'

**Comment by David9591** [comment]
> Model Summary: 224 layers, 7266973 parameters, 0 gradients Traceback (most recent call last): File "E:/Python/yolo-pose/edgeai-yolov5/detect.py", line 202, in detect(opt=opt) File "E:/Python/yolo-pose/edgeai-yolov5/detect.py", line 65, in detect model(torch.zeros(1, 3, imgsz, imgsz).to(device).type_as(next(model.parameters()))) # run once File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 157, in forward return self.forward_once(x, profile) # single-scale inference, train File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 188, in forward_once x = m(x) # run File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl return forward_call(*input, **kwargs) File "E:\Python\yolo-pose\edgeai-yolov5\models\yolo.py", line 64, in forward if self.nkpt is None or self.nkpt==0: File "D:\miniconda\envs\yolo-pose\lib\site-packages\torch\nn\modules\module.py", line 1177, in **getattr** raise AttributeError("'{}' object has no attribute '{}'".format( AttributeError: 'Detect' object has no attribute 'nkpt'

Hello, I also encountered this problem when I tried to export Yolov5m6_pose_640_ti_lite.pt to onnx file. Have you solved it? Can you give me some advice? Thank you

**Comment by nomaad42** [comment]
> @rongfal Hello! Have you solved this problem?

Just use download the proper weights using wget. Then, make sure you're using the right pytorch version as well
