### ISSUE TITLE
where to update the pre/post processing for yolov5s in vision apps?

### ISSUE THREAD

**Issue by hfw6310** [TexasInstruments/edgeai-yolov5#8]
## ❔Question
The original pre/post processing of object detection  in folder vision_apps/apps/dl_demos/app_tidl_od is for Pelee network available at, https://github.com/Robert-JunWang/Pelee. can you please tell me where to update the pre/post processing for yolov5s model in vision_apps/apps/dl_demos/app_tidl_od?
![image](https://user-images.githubusercontent.com/38710029/159241014-5504c939-d4bf-4118-a1aa-1a5c3b271d6f.png)

## Additional context

we use Processor SDK RTOS J721E on TDA4 for developing

**Comment by hfw6310** [comment]
we use Processor SDK RTOS J721E for developing

**Comment by hfw6310** [comment]
we use Processor SDK RTOS J721E on TDA4 for developing

**Comment by debapriyamaji** [comment]
Hi @hfw6310 ,
Are you looing for the mean and variance during input pre-processing? Here are those details:
mean=(0.0, 0.0, 0.0)
scale=(0.003921568627, 0.003921568627, 0.003921568627)

Another important point is to resize the image by preserving the aspect ratio.

You can refer to this file for further details
https://github.com/TexasInstruments/edgeai-benchmark/blob/e626194f3bbac0f74289aa9748bb622666634e3a/configs/detection.py#L164

Regards, Debapriya

**Comment by hfw6310** [comment]
hello @Debapriya,thanks for your reply
![123](https://user-images.githubusercontent.com/38710029/160787777-d3e286c4-ecb0-4247-848e-5910131a8576.png)
  As the above picture shows, we do the developing work based on the linux Processor SDK RTOS J721E 08_01_00, following the section 8.10.4.3 at, https://downloads.ti.com/jacinto7/esd/processor-sdk-rtos-jacinto7/latest/exports/docs/psdk_rtos/docs/user_guide/developer_notes_tidl.html#id11, on development board, I have successfully ran the original app_tidl_od demo which uses deep Pelee network available at, https://github.com/Robert-JunWang/Pelee for object detection. 
  Now I want to replace Pelee network with the yolov5 network based on the app_tidl_od demo, but I don't know how to modify the source code in the linux source code folder '/home/.../ti-processor-sdk-rtos-j721e-evm-08_01_00_13/vision_apps/apps/dl_demos/app_tidl_od' for yolov5 model. can you please tell me where to modify the pre/post processing for yolov5 model or how to run yolov5 model based on app_tidl_od demo on development board ?

**Comment by shyam-j** [comment]
I recommend that you try the GStreamer based EdgeAI SDK to run the imported network instead of OpenVx based Processor SDK 
https://software-dl.ti.com/jacinto7/esd/processor-sdk-linux-sk-tda4vm/08_01_00_02/exports/docs/index.html

**Comment by hfw6310** [comment]
hello @shyam-j, because our project is based on openvx for developing vision algorithms
