### ISSUE TITLE
YOLO-POSE code

### ISSUE THREAD

**Issue by chophilip21** [TexasInstruments/edgeai-yolov5#9]
## ❔Question

Hi, I have read your paper: "**YOLO-Pose: Enhancing YOLO for Multi Person Pose Estimation Using Object
Keypoint Similarity Loss"**, and I was fascinated by the potential of your idea. Your paper is pointing at this repo, but I cannot seem to find any material related to keypoint detection.  All I see is your code related to object detection.

Are you still working on this? Or does the code exist in another branch?

**Comment by debapriyamaji** [comment]
Hi @chophilip21 ,
Thanks for your interest. I will upload the code sometime next month. Will keep you posted on the same.
Regards, Debapriya

**Comment by chophilip21** [comment]
@debapriyamaji Thank you for your response! Will be looking forward to the code update.

**Comment by Bestsongc** [comment]
Hi, I have read your paper: "YOLO-Pose: Enhancing YOLO for Multi Person Pose Estimation Using Object
Keypoint Similarity Loss", and I was fascinated by the potential of your idea. i am looking forward to the code update

**Comment by Jamjamjamjon** [comment]
When will release pose code？ Anticipating it!

**Comment by sly985-love** [comment]
waitting for your code!

**Comment by MatveyMor** [comment]
nice work! waiting for your code and pretrained weights :pray:

**Comment by a-dubbel** [comment]
+1! 🙏

**Comment by backermanaaa** [comment]
Hello, when will release pose code？ Anticipating it!

**Comment by debapriyamaji** [comment]
Thanks, everyone for your interest.  I will release the code by end of this month.

Regards, Debapriya

**Comment by yizhangliu** [comment]
Thanks for your work.  Waitting for your code!

**Comment by wijjj** [comment]
Would be VERY curious as well! Thanks in advance.

**Comment by ZhenpengChenCode** [comment]
Thanks for your work. Waiting for your code!

**Comment by paleomoon** [comment]
Thanks for your work. Waiting for your code!

**Comment by xiakj** [comment]
watching!

**Comment by TanateT** [comment]
waiting for u

**Comment by yizhangliu** [comment]
Maybe we can find what we need from [https://github.com/TexasInstruments/edgeai-yolox](url): 
  human pose and keypoints.

**Comment by Jamjamjamjon** [comment]
> Maybe we can find what we need from [https://github.com/TexasInstruments/edgeai-yolox](url):
> human pose and keypoints.
Nothing there！ ？

**Comment by Jamjamjamjon** [comment]
It’s the end of May, time to release the code! Appreciate it.

**Comment by debapriyamaji** [comment]
Hi All,
Thanks for your interest. I am working on it, I am trying to release it by this weekend. Sorry for the little delay.

Regards, Debapriya

**Comment by Dramazy** [comment]
keep waiting!

**Comment by debapriyamaji** [comment]
Hi All,

Please try out the yolo-pose code from here:
https://github.com/TexasInstruments/edgeai-yolov5/tree/yolo-pose

If you find this repo useful, please consider giving it a star.

Regards, Debapriya

**Comment by yizhangliu** [comment]
You are prefect guy. Thanks.

**Comment by bui-thanh-lam** [comment]
Are there any pretrained weights released?

**Comment by matveymorozov** [comment]
@dizcza 

There is some bug with links. If you copy it from the name, it should work. The correct labels are located YOLOv5-ti-lite Based Models and Ckpts section.

**Small 640:**
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/yolov5s6_640_ti_lite_54p9_82p2/weights/last.pt

**Small 960:**
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/yolov5s6_960_ti_lite_59p7_85p6/weights/last.pt

**Medium 640:**
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/yolov5m6_640_ti_lite_60p5_86p8/weights/best.pt

**Medium 960:**
http://software-dl.ti.com/jacinto7/esd/modelzoo/gplv3/08_02_00_11/edgeai-yolov5/pretrained_models/checkpoints/keypoint/coco/edgeai-yolov5/yolov5m6_960_ti_lite_65p9_88p6/weights/last.pt

**Comment by dizcza** [comment]
@matveymorozov thanks for the hint.

My Chrome browser still refuses to download the links. But I managed to do the trick with `wget`.

**Comment by dizcza** [comment]
> try to copy it and manually pass in search bar

That's exactly what I did. It doesn't work for me.

Anyhow, I successfully downloaded the file with `wget`.

**Comment by dizcza** [comment]
@matveymorozov is it possible to run yolov5s-pose in OpenCV DNN rather than onnxruntime? I've downloaded ONNX-converted model of yours:

```python
    model_path = "yolov5s6_pose_640_ti_lite_54p9_82p2.onnx"
    net = cv2.dnn.readNet(model_path)
```

```
  File "/home/dizcza/Projects/Airtouch/edgeai-yolov5/onnx_inference/yolo_pose_onnx_inference.py", line 143, in inference_video
    net = cv2.dnn.readNet(model_path)
cv2.error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1073: error: (-2:Unspecified error) in function 'handleNode'
> Node [Split@ai.onnx]:(onnx_node!Split_1904) parse error: OpenCV(4.7.0) /io/opencv/modules/dnn/src/onnx/onnx_importer.cpp:1468: error: (-215:Assertion failed) numSplits > 1 in function 'parseSplit'
```

I also tried converting the same model to ONNX manually and got:

```
$ python models/export.py --weights last.pt  --img 640 --batch 1 --simplify --export-nms
Namespace(weights='last.pt', img_size=[640, 640], batch_size=1, grid=False, device='cpu', dynamic=False, simplify=True, export_nms=True)
YOLOv5 � v4.0-76-gae4e0e8 torch 2.0.0+cu117 CPU

Fusing layers... 
Model Summary: 436 layers, 15086540 parameters, 0 gradients
Traceback (most recent call last):
  File "/home/dizcza/Projects/Airtouch/edgeai-yolov5/models/export.py", line 71, in <module>
    y = model(img)  # dry runs
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dizcza/Projects/Airtouch/edgeai-yolov5/models/yolo.py", line 157, in forward
    return self.forward_once(x, profile)  # single-scale inference, train
  File "/home/dizcza/Projects/Airtouch/edgeai-yolov5/models/yolo.py", line 188, in forward_once
    x = m(x)  # run
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/nn/modules/upsampling.py", line 157, in forward
    recompute_scale_factor=self.recompute_scale_factor)
  File "/home/dizcza/miniconda3/envs/yolov7-pose/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'Upsample' object has no attribute 'recompute_scale_factor'
```

**Comment by dizcza** [comment]
Note that onnxruntime works fine. It's just I'm using for something that can be easily used in OpenCV without any additional engines.

**Comment by matveymorozov** [comment]
Actually, I don't know. I just tested it with onnxruntime and Pytorch

**Comment by Mugutech62** [comment]
> Thanks, everyone for your interest.  I will release the code by end of this month.
> 
> Regards, Debapriya

I am having doubt how can i convert my yolo v5 model into yolo ti model

**Comment by MR-STUZHANG** [comment]
> 谢谢大家的关注。我将在本月底之前发布代码。
> 
> 问候，德巴普里亚
I only saw the AP of the detection box in the code, and did not see the AP related calculation of OKS. Can you provide some technical guidance

**Comment by AliasChenYi** [comment]
I have reproduced the result of yolov8s-pose, and the experimental data is very different from yours, with map50 dropping 20% points. My code and data are exactly the same as what you described, and the operation steps are also strictly followed by yours. Therefore, I may have a problem with hyperparameter setting.
Here are my hyperparameter Settings：
task: pose
mode: train
model: ultralytics/cfg/models/v8pose/yolov8-pose.yaml
data: ultralytics/cfg/datasets/coco-pose.yaml
epochs: 300
time: null
patience: 50
batch: 310
imgsz: 640
save: true
save_period: -1
cache: true
device: '0'
workers: 20
project: runs/train
name: yolov8s-pose
exist_ok: false
pretrained: true
optimizer: SGD
verbose: false
seed: 0
deterministic: true
single_cls: true
rect: false
cos_lr: false
close_mosaic: 10
resume: false
amp: true
fraction: 1.0
profile: false
freeze: null
multi_scale: false
overlap_mask: true
mask_ratio: 4
dropout: 0.0
val: true
split: val
save_json: false
save_hybrid: false
conf: null
iou: 0.7
max_det: 300
half: false
dnn: false
plots: true
source: null
vid_stride: 1
stream_buffer: false
visualize: false
augment: false
agnostic_nms: false
classes: null
retina_masks: false
embed: null
show: false
save_frames: false
save_txt: false
save_conf: false
save_crop: false
show_labels: true
show_conf: true
show_boxes: true
line_width: null
format: torchscript
keras: false
optimize: false
int8: false
dynamic: false
simplify: false
opset: null
workspace: 4
nms: false
lr0: 0.01
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 12.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 0.5
mixup: 0.2
copy_paste: 0.0
auto_augment: randaugment
erasing: 0.4
crop_fraction: 1.0
cfg: null
tracker: botsort.yaml
save_dir: runs/train/yolov8s-pose
